module.exports = {
    rules: {
        // Possible Errors
        "no-extra-boolean-cast": [2],
        "no-extra-parens": [2, "all"],
        "no-extra-semi": [2],
        "no-regex-spaces": [2],
        "no-unsafe-negation": [2],

        // Best Practices
        "curly": [2],
        "dot-location": [2, "property"],
        "dot-notation": [2],
        "eqeqeq": [2],
        "no-else-return": [2],
        "no-extra-bind": [2],
        "no-extra-label": [2],
        "no-floating-decimal": [2],
        "no-implicit-coercion": [2],
        "no-multi-spaces": [2],
        "no-unused-labels": [2],
        "no-useless-return": [2],
        "wrap-iife": [2],
        yoda: [2],

        // String Mode
        strict: [2, "never"],

        // Variables
        "no-undef-init": [2],

        // Stylistic Issues
        "array-bracket-spacing": [2],
        "block-spacing": [2],
        "brace-style": [2],
        "capitalized-comments": [2],
        "comma-dangle": [2],
        "comma-spacing": [2],
        "comma-style": [2],
        "computed-property-spacing": [2],
        "eol-last": [2],
        "func-call-spacing": [2],
        "indent": [2, 2],
        "jsx-quotes": [2],
        "key-spacing": [2],
        "keyword-spacing": [2],
        "linebreak-style": [2],
        "lines-around-comment": [2],
        "lines-around-directive": [2],
        "new-parens": [2],
        "newline-after-var": [2],
        "newline-before-return": [2],
        "no-lonely-if": [2],
        "no-multiple-empty-lines": [2],
        "no-trailing-spaces": [2],
        "no-unneeded-ternary": [2],
        "no-whitespace-before-property": [2],
        "nonblock-statement-body-position": [2],
        "object-curly-newline": [2],
        "object-curly-spacing": [2],
        "object-property-newline": [2],
        "one-var-declaration-per-line": [2],
        "operator-assignment": [2],
        "operator-linebreak": [2],
        "padded-blocks": [2, "never"],
        "quote-props": [2, "as-needed"],
        "quotes": [2, "single"],
        "semi": [2],
        "semi-spacing": [2],
        "space-before-blocks": [2],
        "space-before-function-paren": [2, "never"],
        "space-in-parens": [2],
        "space-infix-ops": [2],
        "space-unary-ops": [2],
        "spaced-comment": [2],
        "template-tag-spacing": [2],
        "unicode-bom": [2],
        "wrap-regex": [2],

        // ECMAScript 6
        "arrow-body-style": [2],
        "arrow-parens": [2, "as-needed"],
        "arrow-spacing": [2],
        "generator-star-spacing": [2],
        "no-useless-computed-key": [2],
        "no-useless-rename": [2],
        "no-var": [2],
        "object-shorthand": [2],
        "prefer-arrow-callback": [2],
        "prefer-const": [2],
        "prefer-numeric-literals": [2],
        "prefer-spread": [2],
        "prefer-template": [2],
        "rest-spread-spacing": [2],
        "sort-imports": [2],
        "template-curly-spacing": [2],
        "yield-star-spacing": [2],
    }
};
